### ISSUE TITLE
Slug field not working inside Tab

### ISSUE THREAD

**Issue by jezzdk** [shuvroroy/nova-tabs#1]
I'm not sure if I need to do something, but whenever I put a Slug field inside a tab, the field is not working. I get an error in the console:

```
POST http://localhost/nova-api/undefined/field/slug/preview 404 (Not Found)
```

If I move the field outside the tabs then it works just fine.

This is my code:
```php
return [
    Tabs::make('Post', [
        Tab::make('Details', [
            ID::make(),
            Text::make('Title')->sortable()->required(),
            Slug::make('Slug')->from('Title'),
        ]),
    ]),
];
```

**Comment by shuvroroy** [comment]
This issue is fixed in [v1.1.0](https://github.com/shuvroroy/nova-tabs/releases/tag/v1.1.0) released. Thanks for creating a issue.
