### ISSUE TITLE
Intellisense errors (non-critical)

### ISSUE THREAD

**Issue by jezzdk** [shuvroroy/nova-tabs#2]
There are a bunch of intellisense errors inside the addFields() method, because the TabContract is missing some methods:

![Screenshot 2023-06-27 at 20 50 02](https://github.com/shuvroroy/nova-tabs/assets/139632/6d4a222d-f006-4f0e-ad4e-7391010352aa)

**Comment by shuvroroy** [comment]
This issue is fixed in [v1.1.0](https://github.com/shuvroroy/nova-tabs/releases/tag/v1.1.0) released. Thanks for creating a issue.
