### ISSUE TITLE
Greyed out scroll bar on tabs.

### ISSUE THREAD

**Issue by renzoandredg** [shuvroroy/nova-tabs#4]
For some reason I'm getting a greyed out scroll bar on my tabs.

`public function fields(NovaRequest $request)
    {
        return [

                    new Panel(__('Customer Information'), $this->customerFields()),

            Tabs::make('Workorders', [
                Tab::make(__('Workorder Details'), [

                    ID::make()->sortable(),
            
                    Number::make('Work Order Number', 'wo_number')
                        ->textAlign('left')
                        ->placeholder('Workorder # is randomly generated')
                        ->readOnly()
                        ->sortable(),

                    BelongsTo::make(__('Customer'), 'customer', Customer::class)
                        ->textAlign('left')
                        ->searchable()
                        ->nullable()
                        ->sortable(),

                    Text::make('Problem', 'wo_problem')
                        ->displayUsing(function ($value) {
                            // Capitalize the first letter of each word in the displayed value
                            $capitalizedName = ucwords($value);
                        
                            return $capitalizedName;
                        })
                        ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                            // Capitalize the first letter of each word in the incoming request
                            $value = ucwords($request->{$requestAttribute});
                        
                            // Store the capitalized name
                            $model->{$attribute} = $value;
                        })
                        ->textAlign('left')
                        ->required()
                        ->sortable(),

                    Text::make('Problem Type', 'wo_problemtype')
                        ->textAlign('left')
                        ->required()
                        ->sortable(),

                    Trix::make('Description', 'wo_description')
                        ->withFiles('public')
                        ->textAlign('left')
                        ->alwaysShow()
                        ->required()
                        ->sortable(),

                    Text::make('Customer PO', 'wo_customerpo')
                        ->textAlign('left')
                        ->required()
                        ->sortable(),

                    Text::make('Asset', 'wo_asset')
                        ->textAlign('left')
                        ->required()
                        ->sortable(),

                    Badge::make('Priority', 'wo_priority')
                        ->options([
                            'Low' => 'Low',
                            'Medium' => 'Medium',
                            'High' => 'High',
                        ])
                        ->colors([
                            'Low' => '#2ECC71',
                            'Medium' => '#F1C40F',
                            'High' => '#E74C3C',
                        ])
                        ->required()
                        ->sortable()
                        ->displayUsingLabels(),
                        
                    BelongsTo::make(__('Vendor'), 'User', User::class)
                        ->textAlign('left')
                        ->searchable()
                        ->nullable()
                        ->sortable(),
                        
                    Select::make('Status', 'wo_status')
                        ->options([
                            'Pending' => 'Pending',
                            'Ongoing' => 'Ongoing',
                            'Completed' => 'Completed',
                        ])
                        ->hideFromIndex()
                        ->hideFromDetail()
                        ->hideWhenCreating()
                        ->textAlign('left')
                        ->required()
                        ->sortable(),

                ]),

                Tab::make(__('Timestamps'), [
                        
                    DateTime::make('Created At')
                        ->filterable()
                        ->default(now())
                        ->readonly(true),

                    DateTime::make('Updated At')
                        ->hideFromIndex()
                        ->default(now())
                        ->readonly(true),

                ]),

                Tab::make(__('Others'), [

                    Status::make('Status', 'wo_status')
                        ->sortable()
                        ->loadingWhen(['Ongoing'])
                        ->failedWhen(['Pending']),

                    NotesField::make('Notes')
                        ->placeholder('Add note'),

                ]),
            ])->withToolbar()->showTitle(),
        ];
    }`

![image](https://github.com/shuvroroy/nova-tabs/assets/46542042/644f5bef-0d72-43e6-a1e4-2ddc32366378)

**Comment by shuvroroy** [comment]
@renzoandredg Maybe this causing this issue. try without it
`new Panel(__('Customer Information'), $this->customerFields()),`

**Comment by renzoandredg** [comment]
Tried removing it and I'm still getting the scroll bar which is weird. But anyway, i'll try to figure it out, thanks.

**Comment by renzoandredg** [comment]
Figured it out! Had to upgrade Nova! Sorry for the troubles :)
